### ISSUE TITLE
Referent Merges

### ISSUE THREAD

**Issue by gengel** [washingtonpost/ans-schema#103]
## Problem

Need a way to merge data from one content item to a specific field in another content item.  This  can be generally thought of as a particular post-processing action to be taken when ingesting new content.

## Proposal

Add `post_processors` as an array to all top level content types.  Add `referent_merge` type as a valid post processor.  Each post processor will be applied in sequence after denormalization but before persisting.

## Example

```
{
  "_id": "ABC",
  "type": "story",
  "version": "0.5.8",
  "additional_properties": {
  },
  "post_processors": [
    {
       "type": "merge_reference",
       "referent": {
          "type": "story",
          "id": "DEF",
          "provider": ""
       },
       "source": ".content_elements[0].content",
       "destination": ".additional_properties.foo"
      }
  ]
}

{
  "_id": "DEF",
  "type": "story",
  "version": "0.5.8",
  "content_elements": [
    {
       "type": "text",
       "content": "Now is the time for all good men to come to the aid of their party."
    }
  ]
}

```

would produce, when ingesting ABC:

```
{
  "_id": "ABC",
  "type": "story",
  "version": "0.5.8",
  "additional_properties": {
     "foo": "Now is the time for all good men to come to the aid of their party."
  },
  "post_processors": [
    {
       "type": "merge_reference",
       "referent": {
          "type": "story",
          "id": "DEF",
          "provider": ""
       },
       "source": ".content_elements[0].content",
       "destination": ".additional_properties.foo"
      }
  ]
}
```

**Comment by jmjakes** [comment]
This approach would work nicely for the problem we are trying to solve in the methode-adapter.

**Comment by rgfindl** [comment]
Could this be done as a part of denormalization?  We'll also have to make sure the referent updates works as well.

```

{
  "_id": "ABC",
  "type": "story",
  "version": "0.5.8",
  "additional_properties": {
    "foo": {
      "type": "reference",
      "referent": {
        "type": "story",
        "id": "DEF",
        "provider": "",
        "source": ".content_elements[0].content"
      }
    }
  }
}
```

**Comment by gengel** [comment]
In this example, yes. But I think the key thing for Gregor is that they want to be able to do it on top of existing denormalized data.  E.g., denormalize an image, then denormalize a field from a story on top of the image data

**Comment by rgfindl** [comment]
Got it.  So for referent updates we'll have to perform the following:
- Store the post_processors as well as the referents.
- When a referent update comes in we'll have to replace the referent then perform the post_processors again.
- When a referent update comes in for one of the post_processors we'll have to update the referent.  

Doable but might be messy.  What is the use case?

**Comment by gengel** [comment]
Basically Gregor wants fields from referent stories to be applied on top of references to certain images:

http://jira.wpprivate.com/browse/CA-242
