### ISSUE TITLE
Proposal: denote IS-A relationship between types

### ISSUE THREAD

**Issue by ayepin** [washingtonpost/ans-schema#116]
**Problem**
Information about IS-A relations between types (schemas?) is missing. For example, [story](https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.5.8/story_elements/text.json) contains a collection of [content_elements](https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.5.8/utils/content_element.json) which suppose to be a base type for other element types, like [text](https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.5.8/story_elements/text.json). But there's no formal link between text and content_element types; one can only guess it by a description.

**Proposal**
Denote IS-A relationship between types with "extends" keyword; for ex. [text](https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.5.8/story_elements/text.json) schema will have additional keyword "extends" with the reference to content_element:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.5.8/story_elements/text.json",
    "description": "A textual content element",
    
    "extends": {
        "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.5.8/utils/content_element.json"
    }

    ....
}
```

This will add a missing piece of information and, in addition, this property is supported by a java code-generation tool which can generate pojos out of json schemas.

**Comment by gengel** [comment]
I like this idea. What is the Java code generation tool that uses this?

**Comment by ayepin** [comment]
http://www.jsonschema2pojo.org/
