### ISSUE TITLE
Proposal: Add Named Entities trait

### ISSUE THREAD

**Issue by fenstamaker** [washingtonpost/ans-schema#121]
# Problem

Track Named Entities (things like organization names, people names, and locations) that are mentioned in a given story. This would allow people to search for stories about certain companies or peoples.

# Proposal

```
{
  "title": "Named Entity",
  "type": "object",
  "required": [
    "_id",
    "type"
  ],
  "properties": {
    "_id": {
     "type": "string",
      "description": "The unique identifier for this Named Entity."
    },
    "type": {
      "type": "string",
      "description": "What this is a Named Entity of. E.g. Organization, Person, Location"
    },
  }
}
```

The above would be what the actual object would look like and would go into the utils section. It would need to go into the [clavis_operation](https://github.com/washingtonpost/ans-schema/blob/master/src/main/resources/schema/ans/0.5.8/clavis_operation.json) type and the [taxonomy](https://github.com/washingtonpost/ans-schema/blob/master/src/main/resources/schema/ans/0.5.8/traits/trait_taxonomy.json) type. 

I haven't finalized if _id and type will be the only fields yet. I just wanted to create this proposal now to talk about it.

# Example

```
"named_entities": [{
  "_id": "The Washington Post",
  "type": "organization"
}, {
  "_id": "Marty Baron",
  "type": "person"
}]
```

**Comment by gengel** [comment]
My intuition is to steer away from using the names for the things as the ids for the things, but I don't have a good reason for it.

**Comment by chadmoone** [comment]
I would agree with @gengel's comment. It seems like, depending on the system creating or managing these, that there are likely to be cases where the entities have a separate identifier or two tags/entities could exist for different meanings/contexts of the same word(s).  Or you might have cases where it's stored with ID `marty-baron`, but presented as `Marty Baron`.  So I think separating it out to `_id`, `name`, and `type` is probably better.  If the system using this does not maintain any identifier outside of the name, it can always repeat the value in both fields.

**Comment by gengel** [comment]
Also, do you imagine these going in `.taxonomy.named_entities` or just `.named_entities`?

**Comment by fenstamaker** [comment]
@chadmoone Ah that's a very good point. I was thinking that the service discovering the named entities - in the case of Arc, Clavis - would normalize the name to the id of the entity itself.

So in the Marty Baron example, `Baron`, `Marty Baron`, `Marty` might all normalize to `Marty Baron` which would also serve as the id. But now thinking about it, this would get messing really quickly; it would bring in false positives, mix up similar named entities, etc.

I think your suggestion of having a separate `name` field which is representative of what is in the text and having the `_id` field being the identifier of the actual matched entity is a great idea.

@gengel Yes, sorry if I didn't make that clear. I imagined `named_entities` would live under `.taxonomy.named_entities` like `.taxonomy.keywords` since named entities are essentially super keywords.

**Comment by fenstamaker** [comment]
Ok, so I think the final proposal will be this:
```
{
  "title": "Named Entity",
  "type": "object",
  "required": [
    "_id",
    "name",
    "type"
  ],
  "properties": {
    "_id": {
     "type": "string",
      "description": "A unique identifier for this Named Entity. Can be different from name."
    },
    "name": {
      "type": "string",
      "description": "The actual string of text for the detected Named Entity."
    },
    "type": {
      "type": "string",
      "description": "What this is a Named Entity of. E.g. Organization, Person, Location"
    },
  }
}
```

Using chad's idea of having a separate `_id` to group similar Named Entities. I.E Variations of names and companies can be seen as the same entity. The `name` field will show the direct text of the Named Entity found in the content.
