### ISSUE TITLE
Proposal: Scheduled Publish Information

### ISSUE THREAD

**Issue by gengel** [washingtonpost/ans-schema#122]
## Problem

Information about future publish events is not included on story objects currently.

## Proposal

Include information about future and past publish/unpublish events.  (E.g., Story API & Content Ops API data)  This data would appear on unpublished versions of stories ONLY.

## Example (Updated)

```
{
    "publishing": {
        "has_published_edition": true,
        "editions": {
            "default": {
                "edition": "default",
                "edition_date": "2017-",
                "first_published_date": "2017-03-",
                "published": false
            },
            "print": {
                "edition": "print"
                "publish_date": "2017-03-03",
                "revision_id": "",
                "published": true
            }
        },        ,
        "operations_scheduled": {
            "publish_edition": [{
                "type": "story_operation",
                "operation": "publish_edition",
                "date": "2017-04-15T15:00:00Z",
                "publish_date": "2017-04-01T",
                "display_date": "2017-04-02T",
                "revision_id": "CAIP33ODLZD5LESQ3CH6MLP6IM",
                "editions": [ "default" ]
            }],
            "unpublish_edition": [{
                "type": "story_operation",
                "operation": "unpublish_edition",
                "date": "2017-04-15T15:00:00Z",
                "editions": [ "default" ]
            }]
        }
    }
}
```

**Comment by jpblair** [comment]
- I'm always a little wary of arrays in Elasticsearch since by default, they're squashed into a single index.  Could someone explain the practical use cases where there would be multiple events in `publish` or `unpublish`?
- What happens with this data once the event actually happens?  The case I'm thinking of is if you want to filter for only scheduled content (ie, not including already published content).

**Comment by gengel** [comment]
The practical use case would be if there are separate scheduled publishes to multiple editions.  Which doesn't really happen now, but might in the future.  Certainly in principle there is nothing in Content Ops API (AFAIK) that prevents queueing up mutiple publish requests.

Good question.  Either Content Ops API has to publish to kafka to trigger a deletion of the scheduled event once it happens, which seems reasonable, or the query-writer would actually do a date comparison on the publish date vs now.

**Comment by jpblair** [comment]
Could you remind me how editions work in the Content API?  I think it would be sufficient for us to base our "scheduled" filter on whether there is an entry in `publish` whose `date` is later than now.  But I just want to be sure that there isn't some business reason why we would want it to be more restrictive than a publish to _any_ edition.

Good point, if we check that the date is in the future then I think that should address that case.

**Comment by gengel** [comment]
In the normal workflow, there is one edition called "default" and every time a story gets published, the edition "default" is created/updated.  (Unpublish deletes.)  At various times we've talked about having other editions be published as well (e.g., "print", "mobile") which would mean different iterations of the story could be sent to different destinations, and a story would be available as published in some contexts but not others.  This is technically implemented at the the API level but I don't believe any workflow exists around this yet.  (It's been a feature "we'll need soon" since the project has started)

**Comment by jpblair** [comment]
Thanks for the explanation.  I think it largely comes down to whether we want to make the "scheduled" distinction based on whether any edition is published, or only a specific one (like "default" or "web").  That's a product question we'll need to decide on and get back to you.  If any edition is fine, then this proposal should work.  Otherwise, I'm not sure if it would unless we use the [nested](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/nested.html) mapping type.  Otherwise, any filters we apply aren't guaranteed to all match for the same object in `schedule.publish`.  With that said, maybe using `nested` makes sense regardless in case we want to do that sort of query in the future.

**Comment by cselvaraj** [comment]
The idea I had in my head about this was simply an "operations" attribute that was a list of ANS operations objects.  I don't have an issue with the attribute being "scheduled", but having them separated by publish and unpublish seems locked into the current use case.

For instance, TGAM has asked for not just publish and unpublish, but delete.  If it was just an array of operations objects, we could handle all cases.

Additionally, these objects are not exactly ANS operations objects.  I'd like to avoid adding another type, if possible.

From the view of Content Operations, ideally, I'd like it to have a kafka topic that simply emits these operations objects at the appropriate time, no parsing needed, other than the time.  That means the listeners would be the content sources (Story API, Anglerfish, etc.) and then they'd see the operation and take the appropriate action.  Content Ops wouldn't contact any service directly and doesn't even need to know the business logic of the operations.

Again, that's the ideal I have in my head.  I'm hoping we can move towards that.

**Comment by gengel** [comment]
So, the ANS object on the story doesn't have to map 1-1 with whatever ContentOps emits on kafka.  ContentOps can just post its data and Content API can convert it to its final format -- in that sense, ContentOps doesn't have to worry about it, beyond making sure the data is there.

(My only issue with the ContentOps format, FWIW, is that based on what I see in rtd, the schedule data and the object the schedule applies don't seem to be together):
```
{
  "content_ref": {
                   "ans_object": {
                                   "editions": ["default"],
                                   "revision_id": "<revision id>",
                                   "story_id": "<arc story id>",
                                   "type": "story_operation"
                                 },
                   "id": "<arc story id>",
                   "operation_type": "story_operation"
                 },
  "schedule": [
                {
                  "date": "2016-06-26T17:45:19.970648+00:00",
                  "job_type": "publish"
                }
              ]
}```

The delete case is useful, and if we go with this approach, we should definitely add it as a key under schedule.  The main reason I had the ops types as part of the keypath was to make querying in elasticsearch easier -- if I want to find stories with a scheduled publish date before x, I can just query on schedule.publish.date > x, rather than some object mangling schedule.date > x and schedule.type == 'publish'.  On the other hand, Joseph suggests that we might need to use object-level indexing for this feature anyway, which would make this slightly moot.  

So the alternative I suppose would be:
```
{
  "type": "story",
  "version": "0.5.8",
  "schedule": [
    {
       "type": "schedule_event",
       "event_type": "publish",
       "date": "2017-04-15T15:00:00Z",
       "revision_id": "CAIP33ODLZD5LESQ3CH6MLP6IM",
       "editions": [ "default" ]
    },
    {
       "type": "unpublish_event",
       "event_type": "unpublish",
       "date": "2017-04-15T15:00:00Z",
       "editions": [ "default" ]
     }]
  }
} 
```

Let's see if we can get the ES queries we want with this model?

**Comment by cselvaraj** [comment]
I definitely won't defend the response format for that call in Content Ops.  Almost immediately after release, I realized how bad it was.  But, I was hoping to completely obviate the need for that end point, so I wouldn't look to Content Ops for implementation inspiration.

I'm not completely opposed to keying by operation, but it would be nice to keep consistent with the operation names.  However, "publish_edition" and "unpublish_edition" are the names for the story operations.  Maybe we should make consistent operation names across content types?  Although, I suppose the "delete" operation applies to the story item, whereas the "publish_edition" and "unpublish_edition" operations apply to the edition.  I suppose the story and the editions are separate resources, from that perspective.  Maybe we should reflect that in the operations?

Maybe that's over complicating the situation, but there does seem to be overloading in the story operations: the operations are CRUD operations on story and story edition resources.  Should we separate them?

**Comment by gengel** [comment]
Updated to reflect discussion with @jpblair @cselvaraj
