### ISSUE TITLE
Proposal: Add an Interstitial Link content element (Example)

### ISSUE THREAD

**Issue by gengel** [washingtonpost/ans-schema#62]
Please add a new content element for interstitial links.  These are used within the body an article to link to a specific article that may be related.

An interstitial link differs from related content in that it is placed at a specific position in the body of an article, and thus is best represented as a content element rather than as a sub-item in the related_content field.

```
{
  "type": "story",
  "version": "0.5.5",
  "content_elements": [
    {
      "type": "interstitial-link",
      "url": 'https://www.washingtonpost.com/politics/can-clinton-and-trump-ride-to-big-victories-in-next-weeks-acela-primary/2016/04/20/ea6454fc-064e-11e6-bdcb-0133da18418d_story.html?hpid=hp_rhp-top-table-main_5states-1025a%3Ahomepage%2Fstory",
      "content": "Can Clinton and Trump ride to big victories in next weeks Acela primary?"
    }
  ]
}
```

**Comment by chadmoone** [comment]
Just stumbled upon this.  Thinking ahead, Rainbow has a very similar concept, called either 'embedded story' or 'inline story':

![img_0024 2](https://cloud.githubusercontent.com/assets/149477/18801768/dd4f2992-81b2-11e6-806a-c468d002d269.PNG)

They are used very often.

In the rainbow version, as you can see, we also have support for author and image fields.  Could these potentially be added to this element?

**Comment by gengel** [comment]
We can; But there's an open question as to whether or not the interstitial element will be encouraged or not since Content API now supports including the whole story object as a content element itself. Embedding the whole story object itself would obviously include author, image, etc.  But if it's more useful to rainbow to represent interstitial links explicitly as interstitial links with a subset of fields, then we should add them for sure
