### ISSUE TITLE
Content Element Groups

### ISSUE THREAD

**Issue by gengel** [washingtonpost/ans-schema#84]
## Problem 

ANS has no way to represent image alignment, side by side images, or other relationships between individual content elements.  

## Proposed Solution 

A general group element that indicates a relationship between two or more sub-elements.  

## Example 

```
{
  "type": "story",
  "version": "0.5.8",
  "content_elements": [
    {
      "_id": "1",
      "type": "element_group",
      "version": "0.5.8",
      "content_elements": [
        {
          "_id": "1a",
          "type": "image",
          "url": "http://ichef-1.bbci.co.uk/news/660/cpsprodpb/1325A/production/_88762487_junk_food.jpg"
        },
        {
          "_id": "1b",
          "type": "text",
          "content": "Inventore corrupti reprehenderit sunt eaque fugit repellendus. Saepe architecto totam porro. Voluptatem deserunt sequi corporis. Autem ducimus eligendi ut."
        }
      ]
    }
  ]
}
```

## Pros

* Seemingly accommodates at least two immediate use cases

## Cons

* Pretty bare-bones

**Comment by gengel** [comment]
Updated with `group_type` field.

**Comment by kscoulter** [comment]
External Related Links: https://arcpublishing.atlassian.net/browse/NZME-43
Call to action: https://arcpublishing.atlassian.net/browse/NZME-42
