### ISSUE TITLE
Proposal: Nested blockquotes & credit

### ISSUE THREAD

**Issue by gengel** [washingtonpost/ans-schema#89]
## Problem

Blockquotes are frequently used to excerpt large amounts of content from other sources.  Currently the `blockquote` element includes only one exclusive field, `content` which expects an HTML string.  This makes quotes longer than a single paragraph difficult (either embed the parapgraph breaks within the content as HTML, or have a series of separate `blockquote` elements), it makes mixed-content like images, video difficult (the only option is to render it all to HTML), and it makes nested blockquotes -- an actual use case -- difficult for the same reason.  

Furthermore, when rendered, quotes often have a credit or source associated with them. Currently this is not represented in ANS and requires a separate `text` element, not clearly semantically linked.

## Proposed Solution

Add a `quote` element to ANS.  A `quote` will differ from a `blockquote` in two key ways

* `content_elements` attribute -- Instead of a flat `content` string, this will include a list of sub-elements (similar to a `element_group` or sub-story)
* `citation` -- (Optional) A text element for describing the source of the quote

For convenience, `blockquote` will continue to exist for the ANS 0.5.8 in its current form and be deprecated+upverted in a later release

## Example

```
{
  "type": "quote",
  "content_elements": [
    { 
       "type": "text",
       "content": "Now is the time for all good men to come to the aid of their party."
     },
     {
       "type": "image",
       "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Underwoodfive.jpg/220px-Underwoodfive.jpg"
     }
  ],
  "citation": {
    "type": "text",
    "content": "Charles E. Weller; <em>The Early History of the Typewriter</em>, p. 21 (1918)"
   }
}
```

## Potential concerns

* Should any content elements be forbidden from being included in a `quote`'s content elements?

**Comment by chadmoone** [comment]
👍

**Comment by gengel** [comment]
FWIW: `citation` is optional
