### ISSUE TITLE
Proposal: Ads config

### ISSUE THREAD

**Issue by gengel** [washingtonpost/ans-schema#91]
## Problem

Need a place to store ad configuration.

## Proposal

`ads_config`
* `ad_unit_id`: What WaPo calls `commercial_node`. An identifier with a given page to display ads from a particular source (rather than network, house ads)
* `show_ads`:  A boolean determining whether ads are hidden on the content object

## Example

```
{
  "type": "story",
  "version": "0.5.8",
  "ads": {
    "ad_unit_id": "cool_client",
    "show_ads": true
  }
}
```

**Comment by chadmoone** [comment]
Would this be a property on only `Story`?  Off the top of my head, it seems like at least `Video`, `Gallery`, and `Audio` could have use cases. Maybe there are others as well.

Also, I wonder if `"ads"` should be renamed to better imply that this is metadata, and not actual `Ad`s. Not sure at a glance what our approach has been—something like `"ad_properties"` or is `"ads"` actually more consistent for a case like this?)

**Comment by gengel** [comment]
1) The intent is to add it as a property on any top-level type, so video, gallery, image and audio could all have it
2) `ads_config`? `ad_settings`? I don't really know either

**Comment by chadmoone** [comment]
`ads_config` or `ad_properties` both seem fine to me. Anyone else have a preference?

**Comment by gengel** [comment]
The need for this had disappeared for the moment. I'm closing this for now.
