### ISSUE TITLE
Proposal: Comments Config

### ISSUE THREAD

**Issue by gengel** [washingtonpost/ans-schema#92]
## Problem

Comments can be configured on a per-page basis, and some comment metadata is useful when rendering.

## Proposal

A `comments` object with the following properties (suggested by @StephanieDClark )

* `comments_period` - integer indicating how long (in days) until comments are closed
* `allow_comments` - boolean
* `display_comments` - boolean
* `moderation_required` - boolean

## Example

```
comments: {
  allow_comments: true,
  comments_period: 14,
  display_comments: true,
  moderation_required: false,
}
```

**Comment by tbrick855** [comment]
Just looking at it I can't tell what comments_period is.  Hour, days?  Can that be made more explicit?

**Comment by gengel** [comment]
Good catch; I'll make it clear it is in days

**Comment by gengel** [comment]
Made `comments_period` an integer

**Comment by chadmoone** [comment]
This makes sense to me, but I have the same concern with the naming of the root key as in #91.  Noticing that the wording used to describe both of these proposals was 'config/configuration', I think we should make them `ads_config` and `comments_config`.  Of course, the `count` fields aren't really configuration data, so I suppose we could also do something like `_info` if we wanted to get real semantic, but `_config` is probably fine and should be clear to everyone.

**Comment by gengel** [comment]
Fair enough; changed

**Comment by gengel** [comment]
Per discussion today, I dropped `comments_count` and `comments_count_fuzzy`
