### ISSUE TITLE
Add Oembed response data

### ISSUE THREAD

**Issue by gengel** [washingtonpost/ans-schema#99]
## Problem 

Add an oembed representation to ANS video/image documents.

## Proposal

Should include all general fields, video-specific and photo-specific fields from
http://oembed.com/#section2

* type 
* version 
* title 
* author_name 
* author_url 
* provider_name 
* provider_url 
* cache_age 
* thumbnail_url 
* thumbnail_width 
* thumbnail_height 
* html
* width
* height
* url

## Example
```
{
  "type": "video",
  "version": "0.5.8",
  "headlines": {
    "basic": "My Video"
  },
  
  "oembed": {
    "type": "video",
    "version": "1.0",
    "title": "My Video",
    "author_name": "The Washington Post",
    "author_url": "https://www.washingtonpost.com",
    "provider_name": "The Washington Post",
    "provider_url": "https://video.washingtonpost.com/oembed",
    "cache_age": 86400,
    "thumbnail_url": "https://video.washingtonpost.com/thumbnail/my-video.jpg",
    "thumbnail_width": 640,
    "thumbnail_height": 480,
    "html": "<iframe width=\"560\" height=\"315\" src=\"https://video.washingtonpost.com/video/my-video\" frameborder=\"0\" allowfullscreen></iframe>",
    "width": 1920,
    "height": 1080
  }
}
```

**Comment by vviswa** [comment]
Let's just add 1 field as embed_html so that the other fields are not duplicated.
